version: "3"

services:
  bot-telegram:
    container_name: bot-telegram
    image: python:3.8.3-alpine
    restart: always
    build: .
    environment:
      - TELEGRAM_TOKEN=token-aqui
      - BASE_API_URL=1
    working_dir: /bot-telegram
    volumes:
      - /home/pi/telegram-sheriff/botTelegram/src:/bot-telegram
    command: "python3 -u core.py"
